mainModule
    .constant("appUrl", "http://localhost:8080/")
    .constant("baseUrl", "https://api.themoviedb.org/3")
    .constant("baseUrlMovie", "https://api.themoviedb.org/3/movie/")
    .constant("baseUrlImage", "https://image.tmdb.org/t/p")
    .constant("youtubeWatchUrl", "https://www.youtube.com/watch")
    .constant("authenticateUrl", "https://www.themoviedb.org/authenticate/")
    .constant("apiKey", "4cb65bf8f17aef02911a52f185a5614d")

    .constant("imageSizeList", "/w92")
    .constant("imageSizeCarousel", "/w500")

    .constant("ON_GENRES", "onGenres")
    .constant("ON_SELECTEDGENRES", "onSelectedGenres")
    .constant("ON_MOVIES", "onMovies")
    .constant("ON_IMAGES", "onImages")
    .constant("ON_CAROUSEL", "onCarousel")
    .constant("ON_REVIEWS", "onReviews")
    .constant("ON_SELECTEDMOVIE", "onSelectedMovie")
    .constant("ON_SIMILARMOVIES", "onSimilarMovies")
    .constant("ON_ASSOCIATEDMOVIES", "onAssociatedMovies")
    .constant("ON_RECOMMANDEDMOVIES", "onRecommandedMovies")
    .constant("ON_ACCOUNTDETAILS", "onAccountDetails")
    .constant("ON_VIDEOS", "onVideos")
    .constant("ON_ERROR", "onError")